### PR TITLE
Install CUDA on Windows GPU workers

### LINKED ISSUE #713: Install CUDA on workers
Needed after #712 to make the GPU instance actually useful.

### PR DESCRIPTION
**Pull request by petemoore**
@marco-c does this look ok to you?

I don't think we currently have any Linux workers with GPUs - do you need that too?

Fixes #713

### CODE REVIEW

**Review by lotas — APPROVED** [review]
lgtm

**Comment by petemoore** [comment]
Testing here:

https://community-tc.services.mozilla.com/tasks/fk0HPJP1T26ib2BLB7tkYA

**Comment by petemoore** [comment]
> Testing here:
> 
> https://community-tc.services.mozilla.com/tasks/fk0HPJP1T26ib2BLB7tkYA

Oh dear, it looks like this might have broken things 😬

**Comment by petemoore** [comment]
We will try to test this in staging and see what is going on

**Comment by petemoore** [comment]
Removing from staging in #840...

**Pull request merged**
