### PR TITLE
chore: add binary locations to win2016 worker config

### PR DESCRIPTION
**Pull request by matt-boris**
@tysmith @jschwartzentruber please confirm this updated config works and we'll get this landed. The config has already been applied.

Fixes https://github.com/taskcluster/community-tc-config/issues/695.

### CODE REVIEW

**Comment by petemoore** [comment]
weird, I wonder why that broke, I don't think location changed, did it?

**Comment by matt-boris** [comment]
@petemoore I remember this happening to us at one point and we added it in to the win2022 imageset.

**Comment by matt-boris** [comment]
Got the ok from @jschwartzentruber on matrix, this is working now.

**Comment by matt-boris** [comment]
Previous PR for win2022 https://github.com/taskcluster/community-tc-config/pull/543

**Comment by petemoore** [comment]
you have an impressive memory!

**Pull request merged**
