### PR TITLE
Fix python installation on Windows

### LINKED ISSUE #751: Azure windows images are broken
Taskcluster builds are broken:

1. Python

https://community-tc.services.mozilla.com/tasks/P8DzEsELTHuAyRTAOERjKA/runs/0/logs/live/public/logs/live.log

```
        'python' is not recognized as an internal or external command,
```

2. Permission/path issues (reported by @jschwartzentruber)

Task user cannot access `Administrator` path. (Is it expected though?)

https://community-tc.services.mozilla.com/tasks/IlZwimzgToK9TOCg_MNr9w/runs/0/logs/public/logs/live.log#L137 
```
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps'
```

```diff
123456789101112131415161718192021222324252627282930313233--- passing.txt 2024-06-18 09:26:21.452995987 -0400
+++ failing.txt 2024-06-18 09:26:52.312698868 -0400
@@ -1,8 +1,8 @@
 set PATH=
-C:\Users\task_171779544099340\msys64\opt\python;
-C:\Users\task_171779544099340\msys64\opt\python\Scripts;
-C:\Users\task_171779544099340\msys64\MINGW64\bin;
-C:\Users\task_171779544099340\msys64\usr\bin;
+C:\Users\task_171865188403490\msys64\opt\python;
+C:\Users\task_171865188403490\msys64\opt\python\Scripts;
+C:\Users\task_171865188403490\msys64\MINGW64\bin;
+C:\Users\task_171865188403490\msys64\usr\bin;
 C:\Windows\system32;
 C:\Windows;
 C:\Windows\System32\Wbem;
@@ -10,11 +10,8 @@
 C:\Windows\System32\OpenSSH\;
 C:\Program Files\Amazon\cfn-bootstrap\;
 C:\ProgramData\chocolatey\bin;
-;
 C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;
 ;
-C:\ProgramData\chocolatey\bin;
-;
 C:\Program Files\Vim\vim80;
 C:\go\bin;
 C:\Program Files\Git\cmd;
@@ -22,4 +19,4 @@
 C:\Program Files\Python311;
 C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;
 C:\Program Files\dotnet\;
-C:\Users\task_171779544099340\AppData\Local\Microsoft\WindowsApps 
+C:\Users\task_171865188403490\AppData\Local\Microsoft\WindowsApps 
```

### PR DESCRIPTION
**Pull request by petemoore**
Fixes #751

### CODE REVIEW

**Comment by petemoore** [comment]
Testing in https://community-tc.services.mozilla.com/tasks/ZsxqC-njQ46-8EZUXTKKrg

**Comment by petemoore** [comment]
Exit code was 1622. Added further debugging, rebuilt images, and testing again in https://community-tc.services.mozilla.com/tasks/cdhtCr3UQdCxIwGAMDqnLQ ...

**Comment by petemoore** [comment]
Somehow adding the debug seems to have fixed the issue. Or it is an intermittent issue. Strange!

**Review by lotas — DISMISSED** [review]
🤞

**Comment by petemoore** [comment]
Trying again...

https://community-tc.services.mozilla.com/tasks/d_uBNfDSSImp6iSwuohYXQ

**Review by lotas — APPROVED** [review]

**Pull request merged**
