### PR TITLE
fix: disable edgeupdate service for generic-worker-win2022

### PR DESCRIPTION
**Pull request by tysmith**
This will prevent Microsoft Edge from updating automatically.

Fixes https://github.com/taskcluster/community-tc-config/issues/884.

### CODE REVIEW

**Review by matt-boris — APPROVED** [review]
Nice, thanks! 👍🏻

**Comment by matt-boris** [comment]
@tysmith any reason you closed this?

**Comment by tysmith** [comment]
Oh, no sorry that was a mistake.

**Comment by matt-boris** [comment]
Looks like it merged anyway 😄 I'll rebuild images later this afternoon

**Pull request closed without merging**
