### PR TITLE
Fix for errors in docker image building

### PR DESCRIPTION
**Pull request by petemoore**
See failures in e.g. https://github.com/taskcluster/taskcluster/commit/84fad78f45e09eee1edd3b984517faff00178d25

### CODE REVIEW

**Review by lotas — APPROVED** [review]
thanks for quick fix

**Comment by petemoore** [comment]
I think we decided against this in the end? Do you guys remember?

**Comment by petemoore** [comment]
I _think_ we decided to build using podman instead...

**Comment by matt-boris** [comment]
I think this can be closed, as we just ended up removing `--init`, so we won't see this issue again (from me manually crafting the task to run without `--init` or using `podman`).

https://github.com/taskcluster/taskcluster/pull/7317

**Pull request closed without merging**
