### PR TITLE
Move last remaining Windows workloads from AWS to Azure

### PR DESCRIPTION
**Pull request by petemoore**
At the same time I've updated terminology from  "instance type" to "VM size" in Azure, since it uses different nomenclature to AWS. This has benefit that instance sizes can be specified for AWS at the same time as VM sizes being specified for Azure, and even machine types being specified for Google Cloud, without the properties conflicting with each other. Then when we need to move workers from e.g. AWS to Azure or GCP etc the appropriate instance types / machine types / VM sizes can be retained without conflicting with each other.

### CODE REVIEW

**Comment by petemoore** [comment]
CC @marco-c @glandium FYI - moving last two pools to Azure from AWS

* `proj-git-cinnabar/win2012r2`
* `proj-relman/win2022`

**Review by lotas — DISMISSED** [review]
LGTM

**Review by lotas — APPROVED** [review]

**Review by matt-boris — APPROVED** [review]
👍🏻

**Comment by petemoore** [comment]
```
Updating Role=worker-pool:proj-git-cinnabar/win2012r2
Updating Role=worker-pool:proj-relman/win2022
Updating WorkerPool=proj-git-cinnabar/win2012r2
Updating WorkerPool=proj-relman/win2022
Creating Role=worker-pool:proj-git-cinnabar/windows
Updating Role=repo:github.com/glandium/git-cinnabar:decision-task
Creating WorkerPool=proj-git-cinnabar/windows
```

**Pull request merged**
